# Generated by Django 5.0.4 on 2024-04-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nac',
            new_name='fecha_nacimiento',
        ),
    ]
